apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: pohemami-backend
  app.kubernetes.io/instance: pohemami-backend-instance
  app.kubernetes.io/name: pohemami-backend
